name: athan_times
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  prayers_times: ^0.0.6
  intl: ^0.20.2
  path_provider: ^2.1.5
  fluttertoast: ^8.2.12
  flutter_timezone: ^4.1.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  timezone: ^0.9.4
  flutter_background_service: ^5.1.0
  flutter_foreground_task: ^8.17.0
  logger: ^2.5.0
  app_settings: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Fustat
      fonts:
        - asset: assets/fonts/Fustat-VariableFont_wght.ttf
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle-Regular.ttf
        - asset: assets/fonts/Dongle-Light.ttf
          weight: 100
        - asset: assets/fonts/Dongle-Bold.ttf
          weight: 700
